name: wisetracker
description: This is wisetracker's mobile sdk flutter plugin which is for attribution and inApp analytics. 
version: 0.0.6
homepage: https://github.com/WisetrackerTechteam/Tracker-flutter-package

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: kr.co.wisetracker.wisetracker
        pluginClass: WisetrackerPlugin
      ios:
        pluginClass: WisetrackerPlugin
